# Generated by Django 6.0.3 on 2026-03-19 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='album',
        ),
        migrations.AddField(
            model_name='song',
            name='albums',
            field=models.ManyToManyField(blank=True, related_name='songs', to='music.album'),
        ),
    ]
