# Generated by Django 6.0.3 on 2026-04-21 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_song_generation_task_id_alter_song_audio_file_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='audio_file_path',
            field=models.CharField(max_length=500),
        ),
    ]
