# Generated by Codex on 2026-04-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0004_alter_song_audio_file_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="privacy_level",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("invite_only", "Invite Only"),
                    ("private", "Private"),
                ],
                default="private",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="song",
            name="privacy_level",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("invite_only", "Invite Only"),
                    ("private", "Private"),
                ],
                default="private",
                max_length=50,
            ),
        ),
    ]
