# Generated by Codex on 2026-04-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0005_album_privacy_level_song_privacy_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="invited_emails",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
